USE projeto_financeiro_compras;
DELIMITER //

CREATE PROCEDURE sp_gerador_parcelas(
    IN p_ID_NF_ENTRADA INT,
    IN p_DATA_EMISSAO DATE,
    IN p_VALOR_TOTAL DECIMAL(16,2),
    IN p_ID_CONDICAO INT
)
BEGIN
    DECLARE p_DATA_VENCIMENTO DATE;
    DECLARE p_NUM_PARCELA INT DEFAULT 1;
    DECLARE p_VALOR_PARCELA DECIMAL(16,2);
    DECLARE p_STATUS_PAGAMENTO BOOLEAN DEFAULT 0;
    DECLARE p_QTD_PARCELAS INT;
    DECLARE p_ENTRADA BOOLEAN;

    SELECT ENTRADA, QTD_PARCELAS INTO p_ENTRADA, p_QTD_PARCELAS
    FROM projeto_financeiro_compras.CONDICAO_PAGAMENTO
    WHERE ID_CONDICAO = p_ID_CONDICAO;

    WHILE p_NUM_PARCELA <= p_QTD_PARCELAS DO
        SET p_VALOR_PARCELA = p_VALOR_TOTAL / p_QTD_PARCELAS;
        SET p_DATA_VENCIMENTO = DATE_ADD(p_DATA_EMISSAO, INTERVAL p_NUM_PARCELA - p_ENTRADA MONTH);
        
        INSERT INTO projeto_financeiro_compras.PROGRAMACAO_PAGAMENTO
        (ID_NF_ENTRADA, DATA_VENCIMENTO, DATA_PGT_EFETUADO, NUM_PARCELA, VALOR_PARCELA, VALOR_PARCELA_PAGO, STATUS_PAGAMENTO)
        VALUES (p_ID_NF_ENTRADA, p_DATA_VENCIMENTO, p_DATA_VENCIMENTO, p_NUM_PARCELA, p_VALOR_PARCELA, p_VALOR_PARCELA, p_STATUS_PAGAMENTO);

        SET p_NUM_PARCELA = p_NUM_PARCELA + 1;
    END WHILE;
END //

DELIMITER ;


