use stage_compras;

SELECT * FROM COMPRAS;
select * from TRATAMENTO_PAGAMENTOS_EFETUADOS;
SELECT * FROM TRATAMENTO_COMPRAS_FINAL;
SELECT * FROM VALIDACAO_COMPRAS;
SELECT * FROM VALIDACAO_COMPRAS_REJEITADOS;
SELECT * FROM PAGAMENTOS_EFETUADOS;
SELECT * FROM TRATAMENTO_PAGAMENTOS_EFETUADOS;
SELECT * FROM PAGAMENTOS_EFETUADOS_REJEITADOS;
SELECT * FROM CEP;



TRUNCATE TABLE VALIDACAO_COMPRAS;
TRUNCATE TABLE COMPRAS;
TRUNCATE TABLE VALIDACAO_COMPRAS_REJEITADOS;
TRUNCATE TABLE PAGAMENTOS_EFETUADOS_REJEITADOS;
TRUNCATE TABLE PAGAMENTOS_EFETUADOS;
TRUNCATE TABLE TRATAMENTO_COMPRAS_FINAL;
TRUNCATE TABLE TRATAMENTO_PAGAMENTOS_EFETUADOS;


use projeto_financeiro_compras;
SELECT * FROM FORNECEDORES;
SELECT * FROM TIPO_ENDERECO;
SELECT * FROM CONDICAO_PAGAMENTO;
SELECT * FROM ENDERECOS_FORNECEDORES;
SELECT * FROM NOTAS_FISCAIS_ENTRADA;
SELECT * FROM PROGRAMACAO_PAGAMENTO;
SELECT * FROM HISTORICO_PAGAMENTO;

SET FOREIGN_KEY_CHECKS=0;
truncate table FORNECEDORES;
truncate table ENDERECOS_FORNECEDORES;
truncate table NOTAS_FISCAIS_ENTRADA;
truncate table PROGRAMACAO_PAGAMENTO;
truncate table HISTORICO_PAGAMENTO;
truncate table PAGAMENTOS_EFETUADOS_REJEITADOS1;
truncate table FORNECEDORES;
SET FOREIGN_KEY_CHECKS=1;

select * from sys.foreign_keys

exec gerar_txt @DatabaseName = 'infra_compras'
exec desativar_fk_truncar_txt @DatabaseName = 'infra_compras'
exec ativar_fk @DatabaseName = 'infra_compras'