INSERT INTO projeto_financeiro_compras.CEP 
(CEP, UF, CIDADE, BAIRRO, LOGRADOURO)
SELECT 
    CEP,
    SUBSTRING(UF_ENDERECO, 1, 2),
    COALESCE(CIDADE_ENDERECO, 'N/D'),
    COALESCE(BAIRRO_ENDERECO, 'N/D'),
    COALESCE(NOME_ENDERECO, 'N/D')
FROM 
    stage_compras.CEP;
    
USE projeto_financeiro_compras;
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE CEP;
SET FOREIGN_KEY_CHECKS=1;

SELECT COUNT(*) FROM projeto_financeiro_compras.CEP;