-- TRATAMENTO DA TABELA DE PAGAMENTOS EFETUADOS

USE projeto_financeiro_compras;
DELIMITER //

CREATE PROCEDURE sp_tratamento_pagamentos_efetuados()
BEGIN
    START TRANSACTION;

    INSERT INTO stage_compras.TRATAMENTO_PAGAMENTOS_EFETUADOS
    SELECT
        ID_NF_ENTRADA,
        DATA_VENCIMENTO,
        DATA_PGT_EFETUADO,
        VALOR_PARCELA_PAGO
    FROM
        stage_compras.PAGAMENTOS_EFETUADOS
    WHERE
        ID_NF_ENTRADA IN (SELECT ID_NF_ENTRADA FROM projeto_financeiro_compras.PROGRAMACAO_PAGAMENTO)
        AND DATA_VENCIMENTO IN (SELECT DATA_VENCIMENTO FROM projeto_financeiro_compras.PROGRAMACAO_PAGAMENTO)
        AND DATA_PGT_EFETUADO IS NOT NULL AND DATA_PGT_EFETUADO NOT LIKE '0000-00-00'
        AND VALOR_PARCELA_PAGO IS NOT NULL AND VALOR_PARCELA_PAGO NOT LIKE 0.00;

    COMMIT;
END //

DELIMITER ;

