USE stage_compras;
DELIMITER //

DROP PROCEDURE IF EXISTS sp_tratamento_compras; //
CREATE PROCEDURE sp_tratamento_compras() 
BEGIN
	
	DROP TEMPORARY TABLE IF EXISTS tratamento_1;
    DROP TEMPORARY TABLE IF EXISTS tratamento_2;
    DROP TEMPORARY TABLE IF EXISTS tratamento_3;
   
    -- Tratamento 1
    CREATE TEMPORARY TABLE tratamento_1 AS
	SELECT
		NOME_FORNECEDOR,
		CNPJ_FORNECEDOR,
		EMAIL_FORNECEDOR,
		TELEFONE_FORNECEDOR,
		NUMERO_NF,
		DATA_EMISSAO,
		VALOR_NET,
		VALOR_TRIBUTO,
		VALOR_TOTAL,
		NOME_ITEM,
		QTD_ITEM,
		CONDICAO_PAGAMENTO,
		TRIM(CEP) AS CEP,
		NUM_ENDERECO,
		COMPLEMENTO,
		TIPO_ENDERECO,
		DATA_PROCESSAMENTO
	FROM stage_compras.COMPRAS
	WHERE (NOME_FORNECEDOR IS NOT NULL AND NOME_FORNECEDOR NOT LIKE ''
		AND CNPJ_FORNECEDOR IS NOT NULL AND CNPJ_FORNECEDOR NOT LIKE ''
		AND EMAIL_FORNECEDOR IS NOT NULL AND EMAIL_FORNECEDOR NOT LIKE ''
		AND TELEFONE_FORNECEDOR IS NOT NULL AND TELEFONE_FORNECEDOR NOT LIKE ''
		AND NUMERO_NF IS NOT NULL AND NUMERO_NF NOT LIKE ''
		AND DATA_EMISSAO IS NOT NULL AND DATA_EMISSAO NOT LIKE ''
		AND VALOR_NET IS NOT NULL AND VALOR_NET NOT LIKE ''
		AND VALOR_TRIBUTO IS NOT NULL AND VALOR_TRIBUTO NOT LIKE ''
		AND VALOR_TOTAL IS NOT NULL AND VALOR_TOTAL NOT LIKE ''
		AND NOME_ITEM IS NOT NULL AND NOME_ITEM NOT LIKE ''
		AND QTD_ITEM IS NOT NULL AND QTD_ITEM NOT LIKE ''
		AND CONDICAO_PAGAMENTO IS NOT NULL AND CONDICAO_PAGAMENTO NOT LIKE ''
		AND CEP IS NOT NULL AND CEP NOT LIKE ''
		AND NUM_ENDERECO IS NOT NULL AND NUM_ENDERECO NOT LIKE ''
		AND TIPO_ENDERECO IS NOT NULL AND TIPO_ENDERECO NOT LIKE ''
		AND DATA_PROCESSAMENTO IS NOT NULL AND DATA_PROCESSAMENTO NOT LIKE '');

    -- Tratamento 2
    
    CREATE TEMPORARY TABLE tratamento_2 AS
    SELECT * 
    FROM tratamento_1
    WHERE CEP IN (SELECT CEP FROM projeto_financeiro_compras.CEP);



    -- Tratamento 3
    CREATE TEMPORARY TABLE tratamento_3 AS
    SELECT
        NOME_FORNECEDOR,
        CNPJ_FORNECEDOR,
        EMAIL_FORNECEDOR,
        TELEFONE_FORNECEDOR,
        NUMERO_NF,
        DATA_EMISSAO,
        VALOR_NET,
        VALOR_TRIBUTO,
        VALOR_TOTAL,
        NOME_ITEM,
        QTD_ITEM,
        CASE 
            WHEN SUBSTRING(CONDICAO_PAGAMENTO, 2, 4) NOT LIKE '%ntra%' THEN
                CASE 
                    WHEN CONDICAO_PAGAMENTO LIKE '%90 dias' THEN '30/60/90 dias'
                    WHEN CONDICAO_PAGAMENTO LIKE '%noventa dias' THEN '30/60/90 dias'
                    WHEN CONDICAO_PAGAMENTO LIKE '%60 dias' THEN '30/60 dias' 
                    WHEN CONDICAO_PAGAMENTO LIKE '%vista' THEN 'A vista' 
                    ELSE CONDICAO_PAGAMENTO
                END
            ELSE CONDICAO_PAGAMENTO
        END AS CONDICAO_PAGAMENTO,
        CEP,
        NUM_ENDERECO,
        IFNULL(COMPLEMENTO,'SEM COMPLEMENTO') as COMPLEMENTO,
        TIPO_ENDERECO,
        DATA_PROCESSAMENTO
    FROM tratamento_2
    WHERE CONCAT(DATA_PROCESSAMENTO,NUMERO_NF,CNPJ_FORNECEDOR) 
    NOT IN (SELECT CONCAT(DATA_PROCESSAMENTO,NUM_NF,CNPJ_FORNECEDOR) FROM stage_compras.VALIDACAO_COMPRAS);

    -- Inserir dados na tabela final

CREATE TABLE IF NOT EXISTS stage_compras.TRATAMENTO_COMPRAS_FINAL 
SELECT
    V.NOME_FORNECEDOR,
    V.CNPJ_FORNECEDOR,
    V.EMAIL_FORNECEDOR,
    V.TELEFONE_FORNECEDOR,
    V.NUMERO_NF,
    V.DATA_EMISSAO,
    V.VALOR_NET,
    V.VALOR_TRIBUTO,
    V.VALOR_TOTAL,
    V.NOME_ITEM,
    V.QTD_ITEM,
    CP.ID_CONDICAO AS ID_CONDICAO_PAGAMENTO,
    V.CEP,
    V.NUM_ENDERECO,
    V.COMPLEMENTO,
    V.TIPO_ENDERECO,
    V.DATA_PROCESSAMENTO
FROM tratamento_3 V
JOIN projeto_financeiro_compras.CONDICAO_PAGAMENTO CP ON LOWER(TRIM(CP.DESCRICAO)) = LOWER(TRIM(V.CONDICAO_PAGAMENTO));



    -- Limpar tabelas temporárias
    
    DROP TEMPORARY TABLE IF EXISTS tratamento_1;
    DROP TEMPORARY TABLE IF EXISTS tratamento_2;
    DROP TEMPORARY TABLE IF EXISTS tratamento_3;
END//

DELIMITER ;
